// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkEjen1GEkSCgaNJC8smTa1-1gPpKq3FI',
    appId: '1:1096366452128:web:338e7459558c6fb38a48c5',
    messagingSenderId: '1096366452128',
    projectId: 'ambient-977d0',
    authDomain: 'ambient-977d0.firebaseapp.com',
    storageBucket: 'ambient-977d0.appspot.com',
    measurementId: 'G-DL7PRZ0LKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa3xyNzFhzQPGO3U1L6gBZ1xfETTIwNgw',
    appId: '1:1096366452128:android:f7a077fab7d991868a48c5',
    messagingSenderId: '1096366452128',
    projectId: 'ambient-977d0',
    storageBucket: 'ambient-977d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzqkxabAeNyJoTj_cRE8wnciA91rMnEoI',
    appId: '1:1096366452128:ios:a6e63a30dd1499e28a48c5',
    messagingSenderId: '1096366452128',
    projectId: 'ambient-977d0',
    storageBucket: 'ambient-977d0.appspot.com',
    iosBundleId: 'com.example.ambient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzqkxabAeNyJoTj_cRE8wnciA91rMnEoI',
    appId: '1:1096366452128:ios:a6e63a30dd1499e28a48c5',
    messagingSenderId: '1096366452128',
    projectId: 'ambient-977d0',
    storageBucket: 'ambient-977d0.appspot.com',
    iosBundleId: 'com.example.ambient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkEjen1GEkSCgaNJC8smTa1-1gPpKq3FI',
    appId: '1:1096366452128:web:f33fb589a976b8728a48c5',
    messagingSenderId: '1096366452128',
    projectId: 'ambient-977d0',
    authDomain: 'ambient-977d0.firebaseapp.com',
    storageBucket: 'ambient-977d0.appspot.com',
    measurementId: 'G-TLXGTP8R2X',
  );

}